### ISSUE TITLE
Crash when blueprint API als installed because of spaces (illegal characters) in the mod/datapack filename

### ISSUE THREAD

**Issue by DaeTheDerg** [FusionSwarly/Create-Structures#13]
Removing spaces from the file name seems to fix the issue on client, but not on a dedicated server for some reason, please update the files on modrinth/curseforge to not have spaces in them anyway
e.g. :`CreateStructures-1.20.1_v0.1.1.zip`

this is the crash I get on a server trying to run the forge version of the mod - the same issue also occurs when running a renamed version of the datapack

```
	[07Apr2024 16:36:38.850] [main/WARN] [net.minecraft.server.Main/]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minecraft:create-structures-0.1.1-1.20.1-FORGE.jar
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:195) ~[server-1.20.1-20230612.114412-srg.jar%23417!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:126) ~[loader-47.2.2.jar%2351!/:47.2]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:118) ~[loader-47.2.2.jar%2351!/:47.2]
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.runService(CommonServerLaunchHandler.java:26) ~[loader-47.2.2.jar%2351!/:47.2]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:108) ~[loader-47.2.2.jar%2351!/:47.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2358!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2358!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2358!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2358!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2358!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2358!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2358!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
Caused by: net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minecraft:create-structures-0.1.1-1.20.1-FORGE.jar
	at net.minecraft.resources.ResourceLocation.m_245185_(ResourceLocation.java:236) ~[server-1.20.1-20230612.114412-srg.jar%23417!/:?]
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:38) ~[server-1.20.1-20230612.114412-srg.jar%23417!/:?]
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:42) ~[server-1.20.1-20230612.114412-srg.jar%23417!/:?]
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:46) ~[server-1.20.1-20230612.114412-srg.jar%23417!/:?]
	at com.teamabnormals.blueprint.common.remolder.data.MoldingTypes$MoldingType.remold(MoldingTypes.java:85) ~[blueprint-1.20.1-7.0.3.jar%23282!/:7.0.3]
	at com.teamabnormals.blueprint.common.remolder.RemoldedResourceManager.lambda$getResourceFunction$6(RemoldedResourceManager.java:180) ~[blueprint-1.20.1-7.0.3.jar%23282!/:7.0.3]
	at com.teamabnormals.blueprint.common.remolder.RemoldedResourceManager.m_214159_(RemoldedResourceManager.java:207) ~[blueprint-1.20.1-7.0.3.jar%23282!/:7.0.3]
	at net.minecraft.resources.FileToIdConverter.m_247457_(FileToIdConverter.java:32) ~[server-1.20.1-20230612.114412-srg.jar%23417!/:?]
	at net.minecraft.resources.RegistryDataLoader.m_255048_(RegistryDataLoader.java:134) ~[server-1.20.1-20230612.114412-srg.jar%23417!/:?]
	at net.minecraft.resources.RegistryDataLoader$RegistryData.m_254786_(RegistryDataLoader.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23417!/:?]
	at net.minecraft.resources.RegistryDataLoader.m_254785_(RegistryDataLoader.java:63) ~[server-1.20.1-20230612.114412-srg.jar%23417!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraft.resources.RegistryDataLoader.m_247207_(RegistryDataLoader.java:62) ~[server-1.20.1-20230612.114412-srg.jar%23417!/:?]
	at net.minecraft.server.WorldLoader.m_246152_(WorldLoader.java:54) ~[server-1.20.1-20230612.114412-srg.jar%23417!/:?]
	at net.minecraft.server.WorldLoader.m_245736_(WorldLoader.java:58) ~[server-1.20.1-20230612.114412-srg.jar%23417!/:?]
	at net.minecraft.server.WorldLoader.m_214362_(WorldLoader.java:31) ~[server-1.20.1-20230612.114412-srg.jar%23417!/:?]
	at net.minecraft.server.Main.lambda$main$2(Main.java:167) ~[server-1.20.1-20230612.114412-srg.jar%23417!/:?]
	at net.minecraft.Util.m_214652_(Util.java:777) ~[server-1.20.1-20230612.114412-srg.jar%23417!/:?]
	at net.minecraft.Util.m_214679_(Util.java:772) ~[server-1.20.1-20230612.114412-srg.jar%23417!/:?]
	at net.minecraft.server.Main.main(Main.java:166) ~[server-1.20.1-20230612.114412-srg.jar%23417!/:?]
	... 16 more
```

**Comment by DaeTheDerg** [comment]
Update to this - the issue only occurs when Blueprint is also installed
marking this as an incompatibility instead

**Comment by FusionSwarly** [comment]
Could not replicate. Loaded blueprint with the mod just fine on forge. Also, the mod files shouldn't have any spaces in the name so I'm not sure what the illegal character is.
