### ISSUE TITLE
Warning: Failed to process update information

### ISSUE THREAD

**Issue by Xyphenore** [FusionSwarly/Create-Structures#5]
**Describe the bug**

I got this warning when I start the game: 'Failed to process update information'

**To Reproduce**

- Install the mod.
- Run the game with the output console.
- Warning is printed on console

**Additional context**
- Mod version: 0.1.1 for 1.20.1
- Forge version: 47.1.47
- Create version: 0.5.1b for 1.20.1

**Complet warning**

```
Failed to process update information
java.net.ConnectException: null
	at jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:573) ~[java.net.http:?]
	at jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123) ~[java.net.http:?]
	at net.minecraftforge.fml.VersionChecker$1.openUrlString(VersionChecker.java:139) ~[fmlcore-1.20.1-47.1.47.jar%23163!/:?]
	at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:177) ~[fmlcore-1.20.1-47.1.47.jar%23163!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:114) ~[fmlcore-1.20.1-47.1.47.jar%23163!/:?]
Caused by: java.net.ConnectException
	at jdk.internal.net.http.common.Utils.toConnectException(Utils.java:1055) ~[java.net.http:?]
	at jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:198) ~[java.net.http:?]
	at jdk.internal.net.http.AsyncSSLConnection.connectAsync(AsyncSSLConnection.java:56) ~[java.net.http:?]
	at jdk.internal.net.http.Http2Connection.createAsync(Http2Connection.java:378) ~[java.net.http:?]
	at jdk.internal.net.http.Http2ClientImpl.getConnectionFor(Http2ClientImpl.java:128) ~[java.net.http:?]
	at jdk.internal.net.http.ExchangeImpl.get(ExchangeImpl.java:93) ~[java.net.http:?]
	at jdk.internal.net.http.Exchange.establishExchange(Exchange.java:343) ~[java.net.http:?]
	at jdk.internal.net.http.Exchange.responseAsyncImpl0(Exchange.java:475) ~[java.net.http:?]
	at jdk.internal.net.http.Exchange.responseAsyncImpl(Exchange.java:380) ~[java.net.http:?]
	at jdk.internal.net.http.Exchange.responseAsync(Exchange.java:372) ~[java.net.http:?]
	at jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:408) ~[java.net.http:?]
	at jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:449) ~[java.net.http:?]
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:950) ~[?:?]
	at java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2340) ~[?:?]
	at jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:439) ~[java.net.http:?]
	at jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(MultiExchange.java:341) ~[java.net.http:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) ~[?:?]
	at jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(HttpClientImpl.java:157) ~[java.net.http:?]
	at java.util.concurrent.CompletableFuture.completeAsync(CompletableFuture.java:2673) ~[?:?]
	at jdk.internal.net.http.MultiExchange.responseAsync(MultiExchange.java:294) ~[java.net.http:?]
	at jdk.internal.net.http.HttpClientImpl.sendAsync(HttpClientImpl.java:654) ~[java.net.http:?]
	at jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:552) ~[java.net.http:?]
	... 5 more
Caused by: java.nio.channels.UnresolvedAddressException
	at sun.nio.ch.Net.checkAddress(Net.java:149) ~[?:?]
	at sun.nio.ch.Net.checkAddress(Net.java:157) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:816) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:839) ~[?:?]
	at jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$0(PlainHttpConnection.java:183) ~[java.net.http:?]
	at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]
	at jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:185) ~[java.net.http:?]
	at jdk.internal.net.http.AsyncSSLConnection.connectAsync(AsyncSSLConnection.java:56) ~[java.net.http:?]
	at jdk.internal.net.http.Http2Connection.createAsync(Http2Connection.java:378) ~[java.net.http:?]
	at jdk.internal.net.http.Http2ClientImpl.getConnectionFor(Http2ClientImpl.java:128) ~[java.net.http:?]
	at jdk.internal.net.http.ExchangeImpl.get(ExchangeImpl.java:93) ~[java.net.http:?]
	at jdk.internal.net.http.Exchange.establishExchange(Exchange.java:343) ~[java.net.http:?]
	at jdk.internal.net.http.Exchange.responseAsyncImpl0(Exchange.java:475) ~[java.net.http:?]
	at jdk.internal.net.http.Exchange.responseAsyncImpl(Exchange.java:380) ~[java.net.http:?]
	at jdk.internal.net.http.Exchange.responseAsync(Exchange.java:372) ~[java.net.http:?]
	at jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:408) ~[java.net.http:?]
	at jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:449) ~[java.net.http:?]
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:950) ~[?:?]
	at java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2340) ~[?:?]
	at jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:439) ~[java.net.http:?]
	at jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(MultiExchange.java:341) ~[java.net.http:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) ~[?:?]
	at jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(HttpClientImpl.java:157) ~[java.net.http:?]
	at java.util.concurrent.CompletableFuture.completeAsync(CompletableFuture.java:2673) ~[?:?]
	at jdk.internal.net.http.MultiExchange.responseAsync(MultiExchange.java:294) ~[java.net.http:?]
	at jdk.internal.net.http.HttpClientImpl.sendAsync(HttpClientImpl.java:654) ~[java.net.http:?]
	at jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:552) ~[java.net.http:?]
	... 5 more
```

**Comment by dmptrluke** [comment]
Just wanted to boost this issue. I am also getting the same thing.

`[10:09:07] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [create_structures] Starting version check at https://api.modrinth.comauth/init?url=https://modrinth.com/mod/create-structures/version/e9v4MIpX/updates/IAnP4np7/forge_updates.json
[10:09:07] [Forge Version Check/WARN] [ne.mi.fm.VersionChecker/]: Failed to process update information
java.net.ConnectException: null
        at jdk.internal.net.http.HttpClientImpl.send(Unknown Source) ~[java.net.http:?] {}
        at jdk.internal.net.http.HttpClientFacade.send(Unknown Source) ~[java.net.http:?] {}
        at net.minecraftforge.fml.VersionChecker$1.openUrlString(VersionChecker.java:139) ~[fmlcore-1.20.1-47.2.17.jar%23442!/:?] {}
        at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:177) ~[fmlcore-1.20.1-47.2.17.jar%23442!/:?] {}
        at java.lang.Iterable.forEach(Unknown Source) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:114) ~[fmlcore-1.20.1-47.2.17.jar%23442!/:?] {}
Caused by: java.net.ConnectException
        at jdk.internal.net.http.common.Utils.toConnectException(Unknown Source) ~[java.net.http:?] {}
        at jdk.internal.net.http.PlainHttpConnection.connectAsync(Unknown Source) ~[java.net.http:?] {}
        at jdk.internal.net.http.AsyncSSLConnection.connectAsync(Unknown Source) ~[java.net.http:?] {}
        at jdk.internal.net.http.Http2Connection.createAsync(Unknown Source) ~[java.net.http:?] {}
        at jdk.internal.net.http.Http2ClientImpl.getConnectionFor(Unknown Source) ~[java.net.http:?] {}
        at jdk.internal.net.http.ExchangeImpl.get(Unknown Source) ~[java.net.http:?] {}
        at jdk.internal.net.http.Exchange.establishExchange(Unknown Source) ~[java.net.http:?] {}
        at jdk.internal.net.http.Exchange.responseAsyncImpl0(Unknown Source) ~[java.net.http:?] {}
        at jdk.internal.net.http.Exchange.responseAsyncImpl(Unknown Source) ~[java.net.http:?] {}
        at jdk.internal.net.http.Exchange.responseAsync(Unknown Source) ~[java.net.http:?] {}
        at jdk.internal.net.http.MultiExchange.responseAsyncImpl(Unknown Source) ~[java.net.http:?] {}
        at jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(Unknown Source) ~[java.net.http:?] {}
        at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) ~[?:?] {re:mixin}
        at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source) ~[?:?] {re:mixin}
        at java.util.concurrent.CompletableFuture.handle(Unknown Source) ~[?:?] {re:mixin}
        at jdk.internal.net.http.MultiExchange.responseAsyncImpl(Unknown Source) ~[java.net.http:?] {}
        at jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(Unknown Source) ~[java.net.http:?] {}
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?] {}
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?] {re:mixin}
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?] {}
        at jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(Unknown Source) ~[java.net.http:?] {}
        at java.util.concurrent.CompletableFuture.completeAsync(Unknown Source) ~[?:?] {re:mixin}
        at jdk.internal.net.http.MultiExchange.responseAsync(Unknown Source) ~[java.net.http:?] {}
        at jdk.internal.net.http.HttpClientImpl.sendAsync(Unknown Source) ~[java.net.http:?] {}
        ... 6 more
Caused by: java.nio.channels.UnresolvedAddressException
        at sun.nio.ch.Net.checkAddress(Unknown Source) ~[?:?] {}
        at sun.nio.ch.Net.checkAddress(Unknown Source) ~[?:?] {}
        at sun.nio.ch.SocketChannelImpl.checkRemote(Unknown Source) ~[?:?] {}
        at sun.nio.ch.SocketChannelImpl.connect(Unknown Source) ~[?:?] {}
        at jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$0(Unknown Source) ~[java.net.http:?] {}
        at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?] {}
        at jdk.internal.net.http.PlainHttpConnection.connectAsync(Unknown Source) ~[java.net.http:?] {}
        at jdk.internal.net.http.AsyncSSLConnection.connectAsync(Unknown Source) ~[java.net.http:?] {}
        at jdk.internal.net.http.Http2Connection.createAsync(Unknown Source) ~[java.net.http:?] {}
        at jdk.internal.net.http.Http2ClientImpl.getConnectionFor(Unknown Source) ~[java.net.http:?] {}
        at jdk.internal.net.http.ExchangeImpl.get(Unknown Source) ~[java.net.http:?] {}
        at jdk.internal.net.http.Exchange.establishExchange(Unknown Source) ~[java.net.http:?] {}
        at jdk.internal.net.http.Exchange.responseAsyncImpl0(Unknown Source) ~[java.net.http:?] {}
        at jdk.internal.net.http.Exchange.responseAsyncImpl(Unknown Source) ~[java.net.http:?] {}
        at jdk.internal.net.http.Exchange.responseAsync(Unknown Source) ~[java.net.http:?] {}
        at jdk.internal.net.http.MultiExchange.responseAsyncImpl(Unknown Source) ~[java.net.http:?] {}
        at jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(Unknown Source) ~[java.net.http:?] {}
        at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) ~[?:?] {re:mixin}
        at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source) ~[?:?] {re:mixin}
        at java.util.concurrent.CompletableFuture.handle(Unknown Source) ~[?:?] {re:mixin}
        at jdk.internal.net.http.MultiExchange.responseAsyncImpl(Unknown Source) ~[java.net.http:?] {}
        at jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(Unknown Source) ~[java.net.http:?] {}
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?] {}
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?] {re:mixin}
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?] {}
        at jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(Unknown Source) ~[java.net.http:?] {}
        at java.util.concurrent.CompletableFuture.completeAsync(Unknown Source) ~[?:?] {re:mixin}
        at jdk.internal.net.http.MultiExchange.responseAsync(Unknown Source) ~[java.net.http:?] {}
        at jdk.internal.net.http.HttpClientImpl.sendAsync(Unknown Source) ~[java.net.http:?] {}
        ... 6 more`
